# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be93567a41d6aa66e32531292a96e5cb5fa6bf53c969b7268f255fd3dda7b78745faf999080130ecb4773c5680fba736342bb1ce1baff7838d6117fe391d4a01

test:
  secret_key_base: 5fcd98240acdaae89fcebda4776ec6680ab7da925888b62b87c562bbfcbe6bd234558a6ae3353479aabe2302820fea7d5e34830e2d1c21b3b788445c03d6545b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
